add fixes .github/workflows/ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -222,17 +222,23 @@ jobs:
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
           set -e
-          
+          set -x
           cd /opt/document_service || { echo 'Error: Directory not found'; exit 1; }
           if ! command -v docker-compose &> /dev/null && ! command -v docker compose &> /dev/null; then
-            echo 'Installing docker-compose...'
-            sudo apt-get update
-            sudo apt-get install -y curl
-            sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-            sudo chmod +x /usr/local/bin/docker-compose
+          echo 'Installing docker-compose...'
+          sudo apt-get update
+          sudo apt-get install -y curl
+          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+          sudo chmod +x /usr/local/bin/docker-compose
+          sudo ln -s /usr/local/bin/docker-compose /usr/local/bin/docker-compose
           fi
+          echo "Docker Compose versions:"
+          docker-compose --version || true
+          docker compose version || true
+          docker compose up -d --build
+          EOF
           
-          [ -f docker-compose.yml ] || { echo 'Error: docker-compose.yml not found'; ls -la; exit 1; }
+#          [ -f docker-compose.yml ] || { echo 'Error: docker-compose.yml not found'; ls -la; exit 1; }
           
           sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /opt/document_service
           
